# Generated by Django 5.0.7 on 2025-04-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_crop_harvest_date_livestock_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='animal_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='last_health_check',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='livestock',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
